calc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name="calc"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'add/', views.AddView.as_view(), name="add"),
    url(r'calc/', views.CalcView.as_view(), name="calc"),
]

qpacalc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calc/', include('calc.urls')),
]

calc/models.py
from django.db import models

class Session(models.Model):
    sid = models.CharField(max_length=300)

    def __str__(self):
        return self.sid

# Create your models here.
class Course(models.Model):
    session = models.ForeignKey(Session, on_delete = models.CASCADE)
    courseName = models.CharField(max_length = 10)
    units = models.IntegerField()
    grade = models.CharField(max_length = 3)
    qp = models.IntegerField()

    def __str__(self):
        return self.courseName

calc/views.py
from django.shortcuts import render
from .models import Session, Course
from django.views import generic
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .calculate import *

calculatedTargetQPA = 0
newGradeList = []
desiredQPA = 0
session = None
session_id = None

# Create your views here.
def index(request):
    global calculatedTargetQPA
    global newGradeList
    global desiredQPA
    global session
    global session_id
    request.session.save()
    (units, totalqp, qpa) = (0,0,0)
    if not request.session.exists(request.session.session_key):
        request.session.create()
    if(not Session.objects.filter(sid=request.session.session_key).exists()):
        session = Session(sid=request.session.session_key)
        print("\n\nNEW SESSION", request.session.session_key)
        session.save()
    else:
        print("\n\nSESSION EXISTS", Session.objects.get(sid=request.session.session_key))
        session = Session.objects.get(sid=request.session.session_key)
    if(request.session.session_key != session_id):
        print("\n\n***SESSION WILL BE CHANGED***")
        print("previous session: ",session_id)
        print("next session:", request.session.session_key)
    session_id = request.session.session_key
    courses = session.course_set.all()
    if(len(courses) > 0):
        units = totalUnits(session_id)
        totalqp = totalQP(session_id)
        qpa = calculateQPA(session_id)
    resultsDict = {"units": units, "totalqp": totalqp, "qpa": qpa}
    if(desiredQPA > 0):
        resultsDict["desiredQPA"] = desiredQPA
    if(calculatedTargetQPA > 0):
        resultsDict["calculatedTargetQPA"] = calculatedTargetQPA
    if(len(newGradeList) > 0):
        resultsDict["passingGradeList"] = formatNewGrades(newGradeList)
    context = {"courses": courses, "results": resultsDict}
    calculatedTargetQPA = 0
    newGradeList = []
    desiredQPA = 0
    return render(request, "calc/index.html", context)

class AddView(generic.View):
    def get(self, request):
        global session_id
        session_id = request.session.session_key
        return render(request, "calc/add.html", {"what":None})

    def post(self, request):
        global session
        global session_id
        grade = request.POST["grade"]
        units = request.POST["units"]
        course = request.POST["course"]
        session.course_set.create(courseName = course, units = units, grade = grade, qp=0)
        totalQP(session_id)
        # newCourse = Course(courseName = course, units = units, grade = grade, qp=0)
        # newCourse.save()`
        return HttpResponseRedirect(reverse('calc:index'))

class CalcView(generic.View):
    def get(self, request):
        return render(request, 'calc/calc.html')

    def post(self, request):
        global calculatedTargetQPA
        global newGradeList
        global desiredQPA
        session_id = request.session.session_key
        desiredQPA = float(request.POST["qpa"])
        newGradeList = raiseToQPA(session_id, desiredQPA)
        calculatedTargetQPA = calcDesiredQPA(session_id, newGradeList, desiredQPA)
        return HttpResponseRedirect(reverse('calc:index'))

def formatNewGrades(gradeList):
    for course in gradeList:
        if(isinstance(gradeList[course], int)):
            gradeList[course] = chr(abs(gradeList[course]-4)+65)
    return gradeList

calc/templates/calc/add.html
{% load staticfiles %}
<head>
    <link href="{% static 'calc/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h1>Add course</h1>
    <form action="{% url 'calc:add' %}" method="post">
        {% csrf_token %}
        <input type="text" name="course" placeholder="Enter course number" required>
        <input type="number" name="units" placeholder="How many units?" required>
        <select name="grade">
            <option value="A">A</option>
            <option value="B">B</option>
            <option value="C">C</option>
            <option value="D">D</option>
            <option value="R">R</option>
        </select>
        <input type="submit" value="Add course">
    </form>
</body>

calc/templates/calc/calc.html
{% load staticfiles %}
<head>
    <link href="{% static 'calc/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <form method="post" action="{% url 'calc:calc' %}">
        {% csrf_token %}
        <input type="text" name="qpa" placeholder="Enter desired QPA" required>
        <input type="submit" value="See the grades you need">
    </form>
</body>

calc/templates/calc/index.html
{% load calc_extras %}
{% load staticfiles %}
<head>
    <link href="{% static 'calc/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h1>Course list</h1>
    <a href="{% url 'calc:add' %}">Add a course</a>
    <a href="{% url 'calc:calc' %}">What do I need for a certain QPA?</a>
    <table>
        <tr>
            <th>Course Name</th>
            <th>Grade</th>
            <th>Units</th>
            <th>Quality Points</th>
        </tr>
        {% for course in courses %}
            <tr>
                <td>{{ course.courseName }}</td>
                <td>{{ course.grade }}</td>
                <td>{{ course.units }}</td>
                <td>{{ course.qp }}</td>
            </tr>
        {% endfor %}
    </table>
    <p>units: {{ results.units }}</p>
    <p>quality points: {{ results.totalqp  }}</p>
    <p>qpa: {{ results.qpa }}</p>
    {% if results.desiredQPA %}
        {% if results.passingGradeList %}
            <p>Grades to get >= {{ results.desiredQPA }}: {{ results.passingGradeList }}</p>
        {% endif %}
    {% endif %}
    {% if results.calculatedTargetQPA %}
        <p>QPA with new grades: {{ results.calculatedTargetQPA }}</p>
    {% endif %}
</body>